os: linux
env:
  - SHARD="Build APKs"
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
      - libstdc++6
      - fonts-droid
before_script:
  - git clone --single-branch --branch stable https://github.com/flutter/flutter.git $HOME/flutter
  - bash ./travisbuild.sh
  - export ANDROID_HOME=$HOME/android-sdk
  - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - flutter build apk
after_success:
  - curl -X PUT -u ${OCUSER}:${OCPWD} --data-binary @"build/app/outputs/apk/release/app-release.apk" $OCURL
cache:
  directories:
  - $HOME/.pub-cache